### PR TITLE
Sub task list redux and file structure

### PR DESCRIPTION
**Pull request by VitFL**
- SubTaskList now work and share state using **Redux**
- File structure in my components is changed - now the test files are in a separate folder.
- Minor code refactoring

### CODE REVIEW

**Comment by VitFL** [comment]
Test from TaskDetailsModal.test.js that checks if SubTaskList is rendered inside TaskDetailsModal window is failing since SubTaskList component is now connected using React-Redux... I will be grateful for any advice on how to fix this =)

**Comment by mishalisovskiy** [comment]
Exporting React class by default using connect ruins testing, since it, in fact, is now the connect component wrapping your custom component. Additional simple export of solely the custom component and importing it accordingly in the test file worked for me

**Comment by mishalisovskiy** [comment]
I found this article useful for a deeper understanding of how redux works and how to deal with it when testing.

https://medium.com/netscape/testing-a-react-redux-app-using-jest-and-enzyme-b349324803a9

**Comment by VitFL** [comment]
> Exporting React class by default using connect ruins testing, since it, in fact, is now the connect component wrapping your custom component. Additional simple export of solely the custom component and importing it accordingly in the test file worked for me

Well, the problem is that this is a test for TaskDetailsModal and Stanislav tests if SubTaskList is rendered inside this component... and since SubTaskList is exported using connect... it appears to a test as ConnectedFunction instead of SubTaskList. I know how to test connected components with Jest/Enzym, but I don't understand how to test if connected component is rendered within another component.

**Comment by VitFL** [comment]
> I found this article useful for a deeper understanding of how redux works and how to deal with it when testing.
> 
> https://medium.com/netscape/testing-a-react-redux-app-using-jest-and-enzyme-b349324803a9

Thank you. This is indeed a great article. But, unfortunately, this article doesn't answer my questions =(

**Comment by VitFL** [comment]
As we discussed in PM with @mishalisovskiy and @Larionovv , I removed test from TaskDetailsModal.test.js that checks whether SubTaskList component is rendered inside TaskDetailsModal component. Now all Travis CI checks are passing.

**Pull request merged**
