### PR TITLE
David sort component

### PR DESCRIPTION
**Pull request by da411d**
# SortList component

## Usage
```
<SortList
  storageKey={'someKey'}
  fields={[
    {
      key: 'someName',
      text: 'name',
    },
    {
      key: 'someCreationDate',
      text: 'creation date',
    },
    {
      key: 'somePriority',
      text: 'priority',
    },
  ]}
>
  <Child someName="Lorem" someCreationDate="2019-05-03 12:59:23" somePriority="1"/>
  <Child someName="Ipsum" someCreationDate="2019-05-01 14:45:34" somePriority="3"/>
  <Child someName="Dolor" someCreationDate="2019-05-05 20:54:52" somePriority="2"/>
</SortList>
```

**storageKey** - the key for LocalStorage, where we will save the state of sort field and direction.
It should be unique exactly for every list. I used _board id_ + _column_. 

**fields** - array of objects.
 * **key** - property of children to sort
 * **text** - text for button

### CODE REVIEW

**Comment by Warumo** [comment]
Also I would recommend buttons to have only two mods: normal sorting and reversed. I've tested those buttons for some time and personally I feel that third mode (sorting and button highlight deactivation) very annoying. 

In terms of name I feel like 'Alphabet' naming could be a little bit more optimized in spacing if it will be renamed into sorting by 'Name'.

**Comment by Warumo** [comment]
It seems that you had been implementing __sorting by date__ (based on the last lines of given PR description), but for some reason you came to 'ID' sorting instead. 

In terms of the usefulness sorting by date will be more preferable as there is no use in sorting by ID when it has such a useless value (like this for example: `-Lcc0GCG-dvjcKH6BMEk`). On the other hand 'sorting by date' gives you useful information about when it was created and based on that user will know for how long already he is working on each task.

**Comment by Warumo** [comment]
For some reason both `normal` sorting and `reverse` sorting by `Priority` put tasks with priority `Low` in the middle, but not at the bottom or at the top as it should be.

Screenshot_1 Screenshot_2

**Comment by da411d** [comment]
> It seems that you had been implementing **sorting by date** (based on the last lines of given PR description), but for some reason you came to 'ID' sorting instead.

I did it just for demonstration. Unfortunately, tasks haven't creation date field, so i can`t know when they were added.

**Comment by da411d** [comment]
> For some reason both **normal** sorting and **reverse** sorting by `Priority` put tasks with priority `Low` in the middle, but not at the bottom or at the top as it should be.

Yes. That is because we used strings instead of integer constants. So "**H**igh" < "**L**ow" < "**M**edium" `¯\_(ツ)_/¯`

**Pull request closed without merging**
